version: '3.4'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "28017:27017"
  final-audit-server:
    # build: .
    image: final-audit-server:scaloutions
    restart: always
    ports:
      - "8082:8082"
    depends_on: 
      - mongodb
    links:
      - mongodb
    extra_hosts:
        mongoserver: 0.0.0.0

